# Generated by Django 2.2.3 on 2019-07-16 22:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Citizen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('citizen_id', models.IntegerField()),
                ('town', models.CharField(max_length=100)),
                ('street', models.CharField(max_length=100)),
                ('building', models.CharField(max_length=100)),
                ('appartement', models.IntegerField()),
                ('name', models.CharField(max_length=100)),
                ('birth_date', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('male', 'm'), ('female', 'f')], max_length=6)),
                ('relatives', models.ManyToManyField(to='self')),
            ],
        ),
    ]
