# Generated by Django 2.2.3 on 2019-07-16 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20190716_2317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citizen',
            name='citizen_id',
            field=models.CharField(max_length=1000, primary_key=True, serialize=False),
        ),
    ]
