# Generated by Django 2.2.3 on 2019-08-24 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20190716_2319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citizen',
            name='birth_date',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='citizen',
            name='building',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='citizen',
            name='citizen_id',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='citizen',
            name='name',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='citizen',
            name='street',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='citizen',
            name='town',
            field=models.CharField(max_length=256),
        ),
    ]
